name: Hello World1
on: push
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
      - name: print index.html
        run: cat index.html
  # Test:
  #   runs-on: ubuntu-22.04
  #   needs: Build
  #   steps:
  #     - name: Test phase
  #       run: echo "Running test cases"
  # Deploy:
  #   runs-on: ubuntu-22.04
  #   needs: Test
  #   steps:
  #     - name: Deploy the App
  #       run: echo "Deploying the app"
        
  
