name: Hello World1
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build step
        run:  echo "A demo build"
  Test:
    runs-on: ubuntu-22.04
    needs: Build
    steps:
      - name: Test phase
        run: echo "Running test cases"
  Deploy:
    runs-on: ubuntu-22.04
    needs: Test
    steps:
      - name: Deploy the App
        run: echo "Deploying the app"
        
  
