name: Input Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: chose the enviornment for deploy
        required: true
        default: dev
jobs:
  input-demo:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy the APP
        run: echo"Deploying the application to ${{ inputs.environment }}"
      
        
  
  
